# Development

name = "nft-storage-dev"
main = "./dist/worker.js"
account_id = "fffa4b4363a7e5250af8357087263b3a"
workers_dev = true

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2021-08-23"
compatibility_flags = ["formdata_parser_supports_files"]
no_bundle = true

[vars]
ENV = "dev"
DEBUG = "true"
DATABASE_URL = "http://localhost:3000"

[build]
command = "scripts/cli.js build"

# Staging

[env.staging]
name = "nft-storage-staging"
route = "api-staging.nft.storage/*"
usage_model = "unbound"

[env.staging.vars]
ENV = "staging"
DEBUG = "true"
DATABASE_URL = "https://nft-storage-pgrest-staging.herokuapp.com"

[env.staging.build]
command = "scripts/cli.js build --env staging"
watch_dir = "src"

[env.staging.build.upload]
format = "service-worker"

# Production

[env.production]
name = "nft-storage"
route = "api.nft.storage/*"
usage_model = "unbound"

[env.production.vars]
ENV = "production"
DEBUG = "false"
DATABASE_URL = "https://nft-storage-pgrest-prod.herokuapp.com"

[env.production.build]
command = "scripts/cli.js build --env production"
watch_dir = "src"

[env.production.build.upload]
format = "service-worker"
