version: '3.7'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./external/redis:/data

  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./external/mongo:/data/db

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./external/ipfs:/data
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"