version: '3.6'
services:
  rest:
    image: postgrest/postgrest:v9.0.0
    depends_on:
      - db
    restart: always
    ports:
      - 3000
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMAS: public,cargo
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
  db:
    build:
      context: ./postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    ports:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
  ipfs:
    image: ipfs/go-ipfs:v0.10.0 # update this when go-ipfs M1 macs https://github.com/ipfs/go-ipfs/issues/8645

  cluster:
    image: ipfs/ipfs-cluster:v1.0.0-rc4
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_RESTAPI_BASICAUTHCREDENTIALS: test:test
      CLUSTER_RESTAPI_CORSALLOWEDMETHODS: GET,POST,OPTIONS
      CLUSTER_RESTAPI_CORSALLOWEDHEADERS: authorization
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - 9094
  minio:
    image: quay.io/minio/minio
    command: server /data/minio --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000
      - 9001
